###### user account register
POST  http://localhost:8200/easystore/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "luxdev@devnica.com",
    "password": "Lamisma123*"
}

###### user account login
POST  http://localhost:8200/easystore/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "luxdev@devnica.com",
    "password": "Lamisma123*"
}

###### update personal info
PUT  http://localhost:8200/easystore/v1/user/88a503c6-d1b5-4483-82a3-148e7076e4ac HTTP/1.1
Content-Type: application/json

{
    "phoneNumber": "+502-89906734",
    "dni": "GCL-008967-LKU",
    "firstname": "Test",
    "lastname": "Online",
    "address": "La direccion de siempre donde siempre",
    "birthdate": "1982-10-09" 
}

###### register store
POST  http://localhost:8200/easystore/v1/store HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxYTgyMDczNC02MDc5LTQ2YWMtODhlMy1lNWY2YzQ5Yjk1ODIiLCJleHAiOjE2ODg2NzcwMjgsInJvbGVzIjpbeyJyb2xJZCI6Mywicm9sZSI6ImN1c3RvbWVycyJ9XX0.5G8N82yoreDmYHJcjZNHfTm7L_hbGJFQfnPCBD65kZM

{
    "storeName": "Amores del Arte",
    "address": "Mercado Periferico Modulo H5464",
    "nit": "RT-0087800034",
    "latitude": 13.424460,
    "longitude": -88.441899
}


###### get all stores by ownerId
GET  http://localhost:8200/easystore/v1/store HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxYTgyMDczNC02MDc5LTQ2YWMtODhlMy1lNWY2YzQ5Yjk1ODIiLCJleHAiOjE2ODg2NzcxODcsInJvbGVzIjpbeyJyb2xJZCI6Miwicm9sZSI6Im93bmVycyJ9LHsicm9sSWQiOjMsInJvbGUiOiJjdXN0b21lcnMifV19.RgXpDMOCLRci2DIisUmnPVBfjCv4TRVex_TORJJAeyM

{}