###### user account register
POST  http://localhost:8200/easystore/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "alopez@devnica.com",
    "password": "Lamisma123*"
}

###### user account login
POST  http://localhost:8200/easystore/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "lukas@devnica.com",
    "password": "Lamisma123*"
}

###### update personal info
PUT  http://localhost:8200/easystore/v1/user/0cc1b003-f0a7-4124-b0f6-8418b5b032e0 HTTP/1.1
Content-Type: application/json

{
    "phoneNumber": "+502-897584787",
    "dni": "GCL-009078-LKU",
    "firstname": "Lucas Marcos",
    "lastname": "Marsell",
    "address": "La misma donde siempre he vivido",
    "birthdate": "1978-07-23" 
}

###### register store
POST  http://localhost:8200/easystore/v1/store/0cc1b003-f0a7-4124-b0f6-8418b5b032e0 HTTP/1.1
Content-Type: application/json

{
    "storeName": "La fondita",
    "address": "ustedes ya saben donde queda",
    "nit": "RT-00099988896",
    "latitude": 11.985082,
    "longitude": -86.152449
}


###### get all stores by ownerId
GET  http://localhost:8200/easystore/v1/store/0cc1b003-f0a7-4124-b0f6-8418b5b032e0 HTTP/1.1
Content-Type: application/json

{}